package com.sentinelx.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Structured model capturing the outcome of an asynchronous Google Gemini GenAI shadow scoring evaluation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GeminiShadowResult {

    /**
     * AI-predicted risk score (0 to 100).
     */
    private Integer geminiScore;

    /**
     * AI risk classification tag (e.g. CLEAN, SUSPICIOUS_VELOCITY, ATO_RISK, GEO_MISMATCH, HIGH_VALUE_ANOMALY, SANCTIONED_MERCHANT).
     */
    private String riskCategory;

    /**
     * Contextual justification and semantic reasoning generated by Gemini AI.
     */
    private String reasoning;

    /**
     * Confidence rating of the AI assessment (0.0 to 1.0).
     */
    private Double confidence;

    /**
     * Recommended decision verdict: "ALLOW", "REVIEW", or "BLOCK".
     */
    private String geminiVerdict;
}
